name: Decrypt Bytecode & Generate ABI

on:
  workflow_dispatch:
    inputs:
      bytecode:
        description: 'Contract Bytecode'
        required: true
        type: string

jobs:
  decrypt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Decrypt Script
        run: |
          python decrypt.py "${{ github.event.inputs.bytecode }}"

      - name: Display ABI Output
        run: |
          cat abi_output.json  # Assuming you save your ABI output to a JSON file

